### ISSUE TITLE
Can you add broadcast and antilink 

### ISSUE THREAD

**Issue by iamherok** [FaizBastomi/wbot#11]

**Comment by FaizBastomi** [comment]
antilink has been added in this commit [8b20f4f](https://github.com/FaizBastomi/wbot/commit/8b20f4f28f6470b196eb968e228bc86672eafcc2)

for the broadcast feature you can implement it yourself, if you want to broadcast to all chats you can implement memoryKeyStore, follow the steps on the following link [baileys#implmenting-a-data-store](https://github.com/adiwajshing/Baileys#implementing-a-data-store),
if you only want to broadcast to the group, there is a function `groupFetchAllParticipating` which will retrieve all the data of the group you are currently in, including the group id, you can use your own way here how to broadcast from bot.

hope it's clear.

**Comment by iamherok** [comment]
Oh thnx
