### ISSUE TITLE
[ERROR] Already connected but after a few seconds the session on whatsapp disappeared and logged out

### ISSUE THREAD

**Issue by M-IhsanMaulana** [FaizBastomi/wbot#23]
Saya mencoba untuk connect namun ketika sudah terhubung selang beberapa detik tiba tiba kelogout sendiri dan muncul error terus session di wa nya juga terhapus , error nya kira kira seperti dibawah ini

Untuk Gambar nya :
![Screenshot_20220515_125949](https://user-images.githubusercontent.com/88221660/168460113-c17c7eb2-6abb-4b14-8fba-0359b111b838.png)

Mohon bantuan nya :)

**Comment by FaizBastomi** [comment]
ada 2 kemungkinan,
1. library Baileys yang menyebabkan nya
2. WhatsApp Web yang terus melakukan update

jika memang karena library Baileys, maka harap bersabar sampai versi terbaru nya rilis bisa [dilihat disini](https://github.com/adiwajshing/Baileys/releases), karena maintainer library nya juga sedang melakukan investigasi.

Saya tidak bisa berbuat apa-apa selain menunggu juga,
untuk sementara waktu bisa scan ulang QR nya setelah menghapus file sesi sebelumnya.

**Comment by M-IhsanMaulana** [comment]
okey thanks , kalau ada informasi mengenai hal terkait kabarin yaaa

**Comment by M-IhsanMaulana** [comment]
okey thanks , kalau ada informasi mengenai hal terkait kabarin yaaa

**Comment by M-IhsanMaulana** [comment]
okey thanks , kalau ada informasi mengenai hal terkait kabarin yaaa
