### ISSUE TITLE
.ytv ERROR

### ISSUE THREAD

**Issue by sonzaiekkusu** [FaizBastomi/wbot#24]
![IMG_20220517_102049](https://user-images.githubusercontent.com/61716582/168721776-54fe40c6-7b54-4717-9999-573a0592e10c.jpg)

Error: Request failed with status code 404
at createError (/root/wbot/node_modules/@adiwajshing/baileys/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/wbot/node_modules/@adiwajshing/baileys/node_modules/axios/lib/core/settle.js:17:12)                                                                            at RedirectableRequest.handleResponse (/root/wbot/node_modules/@adiwajshing/baileys/node_modules/axios/lib/adapters/http.js:262:9)                                              at RedirectableRequest.emit (node:events:527:28)                                        at RedirectableRequest._processResponse (/root/wbot/node_modules/follow-redirects/index.js:346:10)                                                                              at ClientRequest.RedirectableRequest._onNativeResponse (/root/wbot/node_modules/follow-redirects/index.js:57:10)                                                                at Object.onceWrapper (node:events:642:26)                                              at ClientRequest.emit (node:events:527:28)                                              at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)         at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)                        at TLSSocket.socketOnData (node:_http_client:494:22)                                    at TLSSocket.emit (node:events:527:28)                                                  at addChunk (node:internal/streams/readable:315:12)                                     at readableAddChunk (node:internal/streams/readable:289:9)                              at TLSSocket.Readable.push (node:internal/streams/readable:228:10)                      at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {                  config: {                                                                                 transitional: {                                                                           silentJSONParsing: true,                                                                forcedJSONParsing: true,                                                                clarifyTimeoutError: false                                                            },                                                                                      adapter: [Function: httpAdapter],                                                       transformRequest: [ [Function: transformRequest] ],                                     transformResponse: [ [Function: transformResponse] ],                                   timeout: 0,                                                                             xsrfCookieName: 'XSRF-TOKEN',                                                           xsrfHeaderName: 'X-XSRF-TOKEN',                                                         maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],                                             headers: {                                                                                Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.24.0'
    },                                                                                      responseType: 'stream',                                                                 method: 'get',
    url: 'https://i.ytimg.com/vi/undefined/0.jpg',
    data: undefined
  },                                                                                      request: <ref *1> ClientRequest {                                                         _events: [Object: null prototype] {
      abort: [Function (anonymous)],                                                          aborted: [Function (anonymous)],
      connect: [Function (anonymous)],                                                        error: [Function (anonymous)],                                                          socket: [Function (anonymous)],
      timeout: [Function (anonymous)],                                                        prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,                                                                        _maxListeners: undefined,
    outputData: [],
    outputSize: 0,                                                                          writable: true,                                                                         destroyed: false,
    _last: true,                                                                            chunkedEncoding: false,
    shouldKeepAlive: false,                                                                 maxRequestsOnConnectionReached: false,                                                  _defaultKeepAlive: true,                                                                useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,                                                                      _hasBody: true,                                                                         _trailer: '',
    finished: true,                                                                         _headerSent: true,                                                                      _closed: false,                                                                         socket: TLSSocket {                                                                       _tlsOptions: [Object],                                                                  _secureEstablished: true,                                                               _securePending: false,                                                                  _newSessionPending: false,                                                              _controlReleased: true,                                                                 secureConnecting: false,                                                                _SNICallback: null,                                                                     servername: 'i.ytimg.com',                                                              alpnProtocol: false,                                                                    authorized: true,                                                                       authorizationError: null,                                                               encrypted: true,                                                                        _events: [Object: null prototype],                                                      _eventsCount: 11,                                                                       connecting: false,                                                                      _hadError: false,                                                                       _parent: null,                                                                          _host: 'i.ytimg.com',                                                                   _readableState: [ReadableState],                                                        _maxListeners: undefined,                                                               _writableState: [WritableState],                                                        allowHalfOpen: false,                                                                   _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',                                                                   server: undefined,                                                                      _server: null,                                                                          ssl: [TLSWrap],
      _requestCert: true,                                                                     _rejectUnauthorized: true,
      parser: [HTTPParser],
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,                                                         [Symbol(async_id_symbol)]: 262,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,                                                                [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,                                                             [Symbol(kCapture)]: false,                                                              [Symbol(kSetNoDelay)]: false,                                                           [Symbol(kSetKeepAlive)]: false,                                                         [Symbol(kSetKeepAliveInitialDelay)]: 0,                                                 [Symbol(kBytesRead)]: 0,                                                                [Symbol(kBytesWritten)]: 0,                                                             [Symbol(connect-options)]: [Object],                                                    [Symbol(RequestTimeout)]: undefined                                                   },                                                                                      _header: 'GET /vi/undefined/0.jpg HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.24.0\r\n' +
      'Host: i.ytimg.com\r\n' +                                                               'Connection: close\r\n' +
      '\r\n',                                                                               _keepAliveTimeout: 0,                                                                   _onPendingData: [Function: nop],
    agent: Agent {                                                                            _events: [Object: null prototype],                                                      _eventsCount: 2,                                                                        _maxListeners: undefined,                                                               defaultPort: 443,                                                                       protocol: 'https:',                                                                     options: [Object: null prototype],                                                      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],                                                      freeSockets: [Object: null prototype] {},                                               keepAliveMsecs: 1000,                                                                   keepAlive: false,                                                                       maxSockets: Infinity,
      maxFreeSockets: 256,                                                                    scheduling: 'lifo',                                                                     maxTotalSockets: Infinity,                                                              totalSocketCount: 1,                                                                    maxCachedSessions: 100,                                                                 _sessionCache: [Object],                                                                [Symbol(kCapture)]: false                                                             },                                                                                      socketPath: undefined,                                                                  method: 'GET',                                                                          maxHeaderSize: undefined,                                                               insecureHTTPParser: undefined,                                                          path: '/vi/undefined/0.jpg',                                                            _ended: false,                                                                          res: IncomingMessage {                                                                    _readableState: [ReadableState],                                                        _events: [Object: null prototype],
      _eventsCount: 1,                                                                        _maxListeners: undefined,                                                               socket: [TLSSocket],                                                                    httpVersionMajor: 1,                                                                    httpVersionMinor: 1,                                                                    httpVersion: '1.1',                                                                     complete: false,                                                                        rawHeaders: [Array],                                                                    rawTrailers: [],                                                                        aborted: false,                                                                         upgrade: false,                                                                         url: '',                                                                                method: null,                                                                           statusCode: 404,
      statusMessage: 'Not Found',                                                             client: [TLSSocket],
      _consuming: false,                                                                      _dumped: false,
      req: [Circular *1],                                                                     responseUrl: 'https://i.ytimg.com/vi/undefined/0.jpg',
      redirects: [],                                                                          [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],                                                           [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,                                                              [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined                                                   },
    aborted: false,                                                                         timeoutCb: null,
    upgradeOrConnect: false,
    parser: HTTPParser {
      '0': null,                                                                              '1': [Function: parserOnHeaders],
      '2': [Function: parserOnHeadersComplete],
      '3': [Function: parserOnBody],                                                          '4': [Function: parserOnMessageComplete],
      '5': null,
      '6': null,                                                                              _headers: [],
      _url: '',                                                                               socket: [TLSSocket],
      incoming: [IncomingMessage],                                                            outgoing: [Circular *1],                                                                maxHeaderPairs: 2000,
      _consumed: false,
      onIncoming: [Function: parserOnIncomingClient],                                         [Symbol(resource_symbol)]: [HTTPClientAsyncResource]                                  },                                                                                      maxHeadersCount: null,                                                                  reusedSocket: false,                                                                    host: 'i.ytimg.com',                                                                    protocol: 'https:',                                                                     _redirectable: Writable {                                                                 _writableState: [WritableState],                                                        _events: [Object: null prototype],                                                      _eventsCount: 2,                                                                        _maxListeners: undefined,                                                               _options: [Object],                                                                     _ended: true,                                                                           _ending: true,                                                                          _redirectCount: 0,                                                                      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],                                              _currentRequest: [Circular *1],                                                         _currentUrl: 'https://i.ytimg.com/vi/undefined/0.jpg',
      [Symbol(kCapture)]: false                                                             },                                                                                      [Symbol(kCapture)]: false,                                                              [Symbol(kNeedDrain)]: false,                                                            [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {                                         accept: [Array],                                                                        'user-agent': [Array],
      host: [Array]                                                                         }
  },                                                                                      response: {
    status: 404,                                                                            statusText: 'Not Found',
    headers: {
      vary: 'Origin',
      'timing-allow-origin': '*',
      'cross-origin-resource-policy': 'cross-origin',
      'content-type': 'image/jpeg',
      date: 'Tue, 17 May 2022 03:15:28 GMT',
      expires: 'Tue, 17 May 2022 03:15:58 GMT',
      'cache-control': 'public, max-age=30',
      'x-content-type-options': 'nosniff',
      server: 'sffe',
      'content-length': '1097',
      'x-xss-protection': '0',
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      connection: 'close'
    },
    config: {
      transitional: [Object],                                                                 adapter: [Function: httpAdapter],                                                       transformRequest: [Array],                                                              transformResponse: [Array],                                                             timeout: 0,                                                                             xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',                                                         maxContentLength: -1,
      maxBodyLength: -1,                                                                      validateStatus: [Function: validateStatus],
      headers: [Object],                                                                      responseType: 'stream',
      method: 'get',                                                                          url: 'https://i.ytimg.com/vi/undefined/0.jpg',
      data: undefined                                                                       },
    request: <ref *1> ClientRequest {                                                         _events: [Object: null prototype],                                                      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],                                                                         outputSize: 0,                                                                          writable: true,                                                                         destroyed: false,                                                                       _last: true,                                                                            chunkedEncoding: false,                                                                 shouldKeepAlive: false,                                                                 maxRequestsOnConnectionReached: false,                                                  _defaultKeepAlive: true,                                                                useChunkedEncodingByDefault: false,                                                     sendDate: false,                                                                        _removedConnection: false,                                                              _removedContLen: false,                                                                 _removedTE: false,                                                                      _contentLength: 0,                                                                      _hasBody: true,                                                                         _trailer: '',                                                                           finished: true,
      _headerSent: true,                                                                      _closed: false,                                                                         socket: [TLSSocket],
      _header: 'GET /vi/undefined/0.jpg HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +                                       'User-Agent: axios/0.24.0\r\n' +                                                        'Host: i.ytimg.com\r\n' +                                                               'Connection: close\r\n' +                                                               '\r\n',                                                                               _keepAliveTimeout: 0,                                                                   _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,                                                                  method: 'GET',                                                                          maxHeaderSize: undefined,                                                               insecureHTTPParser: undefined,                                                          path: '/vi/undefined/0.jpg',                                                            _ended: false,                                                                          res: [IncomingMessage],                                                                 aborted: false,                                                                         timeoutCb: null,                                                                        upgradeOrConnect: false,
      parser: [HTTPParser],                                                                   maxHeadersCount: null,
      reusedSocket: false,                                                                    host: 'i.ytimg.com',                                                                    protocol: 'https:',
      _redirectable: [Writable],                                                              [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,                                                                    [Symbol(kOutHeaders)]: [Object: null prototype]
    },                                                                                      data: IncomingMessage {                                                                   _readableState: [ReadableState],                                                        _events: [Object: null prototype],                                                      _eventsCount: 1,
      _maxListeners: undefined,                                                               socket: [TLSSocket],                                                                    httpVersionMajor: 1,                                                                    httpVersionMinor: 1,                                                                    httpVersion: '1.1',                                                                     complete: false,                                                                        rawHeaders: [Array],                                                                    rawTrailers: [],                                                                        aborted: false,
      upgrade: false,                                                                         url: '',                                                                                method: null,
      statusCode: 404,                                                                        statusMessage: 'Not Found',                                                             client: [TLSSocket],                                                                    _consuming: false,                                                                      _dumped: false,                                                                         req: [ClientRequest],
      responseUrl: 'https://i.ytimg.com/vi/undefined/0.jpg',                                  redirects: [],
      [Symbol(kCapture)]: false,                                                              [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 26,                                                            [Symbol(kTrailers)]: null,                                                              [Symbol(kTrailersCount)]: 0,                                                            [Symbol(RequestTimeout)]: undefined                                                   }                                                                                     },                                                                                      isAxiosError: true,                                                                     toJSON: [Function: toJSON]                                                            }

**Comment by FaizBastomi** [comment]
videonya memang tidak dapat di download

**Comment by sonzaiekkusu** [comment]
> videonya memang tidak dapat di download

Gabisa masukin YT cokkie ya, kalo YT premium kn bisa d download ya?

**Comment by sonzaiekkusu** [comment]
> videonya memang tidak dapat di download

Oke deh nice ingfo

**Comment by FaizBastomi** [comment]
> > videonya memang tidak dapat di download
> 
> Gabisa masukin YT cokkie ya, kalo YT premium kn bisa d download ya?

kebetulan pakainya layanan online [yt1s.com](https://yt1s.com), jadi ga perlu cookie
untuk masalah bisa di download atau tidak tergantung di API web nya, kadang memang dari sana nya eror

**Comment by sonzaiekkusu** [comment]
> > > videonya memang tidak dapat di download
> > 
> > 
> > Gabisa masukin YT cokkie ya, kalo YT premium kn bisa d download ya?
> 
> kebetulan pakainya layanan online [yt1s.com](https://yt1s.com), jadi ga perlu cookie untuk masalah bisa di download atau tidak tergantung di API web nya, kadang memang dari sana nya eror

okey thanks pa penjelasannya
