### ISSUE TITLE
how to get youtube and instagram cookie?

### ISSUE THREAD

**Issue by manishkumar1601** [FaizBastomi/wbot#3]
how to get youtube and instagram cookie? can you give me a video

**Comment by FaizBastomi** [comment]
Open YouTube and Instagram on Desktop Browser and open **Dev Tools (CTRL+SHIFT+I)**
Go to **Network Tab** search for **Document Record (youtube.com and instagram.com)**
Scroll down search **Headers Request > cookie**, copy that's cookies value.

Make sure before copy instagram cookies value, you must login first to your account,
**DON'T PUBLISH YOUR COOKIES ONLINE, MIGHT SOMEONE ABUSE YOUR COOKIES.**
