### ISSUE TITLE
Railways?

### ISSUE THREAD

**Issue by Hbz-Dev** [FaizBastomi/wbot#6]
Support railways ga ngab?

**Comment by benyrwnn** [comment]
yes

**Comment by FaizBastomi** [comment]
sepertinya tidak, saya juga kurang yakin karena di repo ini ada modul yang di ban dari railways
contohnya **yt-search** dan **ytdl-core**, mungkin kalau mau dijalankan disana butuh sedikit edit di bagian yang menyangkut **yt-search** itu.

**Comment by Hbz-Dev** [comment]
> sepertinya tidak, saya juga kurang yakin karena di repo ini ada modul yang di ban dari railways contohnya **yt-search** dan **ytdl-core**, mungkin kalau mau dijalankan disana butuh sedikit edit di bagian yang menyangkut **yt-search** itu.

Baiklah terimakasih
